version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      # ソースコードのチェックアウト
      - checkout

      # pytestインストール
      - run: |
          python3.6 -m venv venv
          source ./venv/bin/activate
          python test_calculations.py --junit-xml=test-results/pytest.xml
          pip install pytest
      - store_test_results:
          path: test-results
