version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      # ソースコードのチェックアウト
      - checkout

      # pytestインストール
      - run: |
          python3.6 -m venv venv
          source ./venv/bin/activate
          pip install django==1.11.7
          pip install sphinx
          make html
          cd cafe/apps
          # マイグレーションの実行
          python manage.py migrate
          # Djangoのテストの実行
          python manage.py test
      - store_artifacts:
          path: _build/html